sudo: required
# Tell the travis that we need super user permission

services: 
  - docker # tell travis we need docker

before_install:
  - docker build -t development_image -f dockerfile.dev .
  # Build the image for development container

  - docker run -e CI=true development_image npm run test